In [1]:
import tensorflow as tf

In [2]:
import tensorflow.keras.layers as layers
from tensorflow import keras

In [3]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))


In [4]:
x = tf.keras.Input(shape=(32,))
h1 = layers.Dense(32, activation="relu")(x)
h2 = layers.Dense(32, activation="relu")(h1)
y = layers.Dense(10, activation="softmax")(h2)

model_sample_2 = tf.keras.models.Model(x,y)

model_sample_2.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_3 (Dense)             (None, 32)                1056      
                                                                 
 dense_4 (Dense)             (None, 32)                1056      
                                                                 
 dense_5 (Dense)             (None, 10)                330       
                                                                 
Total params: 2,442
Trainable params: 2,442
Non-trainable params: 0
_________________________________________________________________


In [5]:
layers.Conv2D(64,[1,1],2,padding='same',activation="relu")

In [6]:
layers.MaxPooling2D(pool_size=(2,2),strides=(2,1))

In [7]:
import numpy as np

In [8]:
inputs = tf.keras.Input(shape=(3, 1))
lstm = layers.LSTM(1, return_sequences=True)(inputs)
model_lstm_1 = tf.keras.models.Model(inputs=inputs, outputs=lstm)

inputs = tf.keras.Input(shape=(3, 1))
lstm = layers.LSTM(1, return_sequences=False)(inputs)
model_lstm_2 = tf.keras.models.Model(inputs=inputs, outputs=lstm)

data = [[[0.1],
        [0.2],
        [0.3]]]
print(data)
print("output when return_sequences is set to True", model_lstm_1.predict(data))
print("output when return_sequences is set to False", model_lstm_1.predict(data))

[[[0.1], [0.2], [0.3]]]
1/1 [==============================] - 7s 7s/step
output when return_sequences is set to True [[[-0.02121617]
  [-0.05239021]
  [-0.08641541]]]
1/1 [==============================] - 0s 45ms/step
output when return_sequences is set to False [[[-0.02121617]
  [-0.05239021]
  [-0.08641541]]]


In [9]:
tf.keras.layers.LSTM(16, return_sequences=True)

x = tf.keras.Input((None, 3))
y = layers.RNN(layers.LSTMCell(16))(x)
model_lstm_3 = tf.keras.Model(x,y)

model = tf.keras.Sequential()
model.add(layers.Dense(10, activation="softmax"))

model_lstm_3.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, None, 3)]         0         
                                                                 
 rnn (RNN)                   (None, 16)                1280      
                                                                 
Total params: 1,280
Trainable params: 1,280
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss=tf.keras.losses.categorical_crossentropy, 
    metrics=[tf.keras.metrics.categorical_accuracy])


In [11]:
train_x = np.random.random((1000, 36))
train_y = np.random.random((1000, 10))
val_x = np.random.random((200, 36))
val_y = np.random.random((200, 10))

model.fit(train_x, train_y, epochs=10, batch_size=100,
         validation_data=(val_x, val_y))

Epoch 1/10
10/10 [==============================] - 3s 43ms/step - loss: 12.5908 - categorical_accuracy: 0.0870 - val_loss: 12.6131 - val_categorical_accuracy: 0.1000
Epoch 2/10
10/10 [==============================] - 0s 6ms/step - loss: 12.5899 - categorical_accuracy: 0.0870 - val_loss: 12.6121 - val_categorical_accuracy: 0.1000
Epoch 3/10
10/10 [==============================] - 0s 5ms/step - loss: 12.5898 - categorical_accuracy: 0.0870 - val_loss: 12.6120 - val_categorical_accuracy: 0.1000
Epoch 4/10
10/10 [==============================] - 0s 5ms/step - loss: 12.5881 - categorical_accuracy: 0.0870 - val_loss: 12.6098 - val_categorical_accuracy: 0.1000
Epoch 5/10
10/10 [==============================] - 0s 6ms/step - loss: 12.5872 - categorical_accuracy: 0.0870 - val_loss: 12.6100 - val_categorical_accuracy: 0.1000
Epoch 6/10
10/10 [==============================] - 0s 5ms/step - loss: 12.5875 - categorical_accuracy: 0.0870 - val_loss: 12.6101 - val_categorical_accuracy: 0.1000
Epo

In [12]:
test_x = np.random.random((1000, 36))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)

32/32 [==============================] - 0s 2ms/step - loss: 12.5958 - categorical_accuracy: 0.1130


[12.595813751220703, 0.11299999803304672]

In [15]:
pre_x = np.random.random((10, 36))
result = model.predict(test_x,)
print(result)

32/32 [==============================] - 0s 1ms/step
[[0.05546078 0.12379247 0.0646968  ... 0.09343503 0.0755486  0.04510788]
 [0.02958948 0.05486373 0.04553977 ... 0.10218485 0.1127058  0.01890107]
 [0.05537532 0.13867564 0.06323746 ... 0.09637002 0.0617594  0.04875376]
 ...
 [0.08738694 0.07340464 0.04599665 ... 0.11434118 0.06346446 0.04524622]
 [0.03010909 0.04954219 0.04237186 ... 0.16082841 0.06504417 0.01820066]
 [0.06165169 0.06586759 0.07250672 ... 0.06458043 0.1149959  0.06928828]]


In [16]:
import os

In [18]:
mode
model_path = os.path.join(root_path,'the_save_model.h5')

model.save('./model/the_save_model.h5')
model.save(model_path)

new_model = tf.keras.models.load_model('./model/the_save_model.h5')

new_model = tf.keras.models.load_model(model_path)

new_prediction = new_model.predict(test_x)

np.testing.assert_allclose(result, new_prediction, atol=1e-6)

32/32 [==============================] - 0s 2ms/step


In [20]:
model.save_weights('.model/model_weights')
model.save_weights('.model/model_weights.h5')

weight_path = os.path.join(root_path, 'model_weights')
weighth5_path = os.path.join(root_path, 'model_weight.h5')

model.save_weights(weight_path)
model.save_weights(weighth5_path)

model.load_weights('.model/model_weights')
model.load_weights('.model/model_weights.h5')

model.load_weights(weight_path)
model.load_weights(weighth5_path)