In [34]:
import tensorflow as tf

In [35]:
print(tf.__version__)

2.9.1


In [36]:
const_a = tf.constant([[1, 2, 3, 4]], shape = [2,2], dtype=tf.float32)
print(const_a)
print("Value of the constant const_a:", tf.get_static_value(const_a))
print("Data type of the constant const_a:", const_a.dtype)
print("Shape of the constant const_a:", const_a.shape)
print("Name of the device that is to generate the constant const_a:", tf.device(const_a))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Value of the constant const_a: [[1. 2.]
 [3. 4.]]
Data type of the constant const_a: <dtype: 'float32'>
Shape of the constant const_a: (2, 2)
Name of the device that is to generate the constant const_a: <tensorflow.python.eager.context._EagerDeviceContext object at 0x0000021568C8C180>


In [37]:
zeros_b = tf.zeros(shape=[2,3], dtype=tf.int32)
print(zeros_b)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [38]:
zeros_a = tf.zeros_like(const_a)
print(zeros_a)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [39]:
fill_d = tf.fill([3,3], 8)
print(fill_d)

tf.Tensor(
[[8 8 8]
 [8 8 8]
 [8 8 8]], shape=(3, 3), dtype=int32)


In [40]:
random_e = tf.random.normal([5,6], mean=0, stddev=1.0, seed=1)
print(random_e)

tf.Tensor(
[[ 0.14471158 -0.58528894  0.22138429 -0.7899326  -0.5778271  -1.4649404 ]
 [-0.20476936 -0.34681118  0.00890026 -1.478669    1.3321851   1.8828119 ]
 [-1.3230424   0.2293617   0.24668725 -0.42386568  0.46550387 -0.8185642 ]
 [-1.5173712   0.47069296  0.11204629  0.3128802  -0.07627326  0.21555018]
 [-1.863655    1.3489391  -0.33752885 -0.32774165 -1.8594182  -0.6946216 ]], shape=(5, 6), dtype=float32)


In [41]:
list_f = [1,2,3,4,5,6]
print(type(list_f))

<class 'list'>


In [42]:
tensor_f = tf.convert_to_tensor(list_f, dtype=tf.float32)
print(tensor_f)

tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)


In [43]:
var_1 = tf.Variable(tf.ones([2,3]))
print(var_1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>


In [44]:
print("Value Of the variable = ", var_1)

Value Of the variable =  <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>


In [45]:
var_2 = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
print("Value of the variable var_1 after the assignment:" ,var_2)

Value of the variable var_1 after the assignment: <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>


In [46]:
var_3 = tf.Variable([[2., 3., 4.], [5., 6., 7.]])
print(var_3)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>


In [47]:
tensor_h = tf.random.normal([4, 100, 100, 3], dtype=tf.float32)
print(tensor_h)

tf.Tensor(
[[[[ 6.53053895e-02  1.16006529e+00 -1.83976543e+00]
   [-1.35930789e+00 -1.00495124e+00 -1.21588933e+00]
   [-6.46750152e-01 -8.22716594e-01 -1.13273835e+00]
   ...
   [ 6.94982350e-01  3.07627702e+00 -1.73715148e-02]
   [-1.41668066e-01  1.94768488e+00 -2.64783561e-01]
   [-2.20702648e-01 -1.73206255e-01 -4.03073817e-01]]

  [[-7.13319838e-01 -1.09166205e+00 -1.62083089e+00]
   [-4.60682273e-01  1.88821721e+00 -4.50883567e-01]
   [ 1.51073337e-01  1.30773175e+00 -1.52539283e-01]
   ...
   [ 1.16286695e+00  8.69000256e-01  2.15855539e-01]
   [-1.07942915e+00  1.15526688e+00  7.77809441e-01]
   [-1.42557994e-02  2.45075434e-01 -5.87552547e-01]]

  [[ 2.34675837e+00 -5.80247976e-02 -1.09814060e+00]
   [ 4.68621373e-01  1.52858782e+00  5.42201042e-01]
   [-1.78422555e-01  1.12338901e+00 -1.96370721e+00]
   ...
   [ 4.25198883e-01 -6.64527059e-01 -2.57852286e-01]
   [-1.90871584e+00 -7.45631874e-01  7.98172832e-01]
   [-2.27147147e-01 -9.60710585e-01 -7.46537268e-01]]

  ...

 

In [48]:
tensor_h[0,:,1:]

<tf.Tensor: shape=(100, 99, 3), dtype=float32, numpy=
array([[[-1.3593079e+00, -1.0049512e+00, -1.2158893e+00],
        [-6.4675015e-01, -8.2271659e-01, -1.1327384e+00],
        [ 1.5016907e+00, -4.5928290e-01, -8.8590103e-01],
        ...,
        [ 6.9498235e-01,  3.0762770e+00, -1.7371515e-02],
        [-1.4166807e-01,  1.9476849e+00, -2.6478356e-01],
        [-2.2070265e-01, -1.7320625e-01, -4.0307382e-01]],

       [[-4.6068227e-01,  1.8882172e+00, -4.5088357e-01],
        [ 1.5107334e-01,  1.3077317e+00, -1.5253928e-01],
        [ 1.0838209e+00,  1.4407588e+00, -7.2806221e-01],
        ...,
        [ 1.1628670e+00,  8.6900026e-01,  2.1585554e-01],
        [-1.0794291e+00,  1.1552669e+00,  7.7780944e-01],
        [-1.4255799e-02,  2.4507543e-01, -5.8755255e-01]],

       [[ 4.6862137e-01,  1.5285878e+00,  5.4220104e-01],
        [-1.7842256e-01,  1.1233890e+00, -1.9637072e+00],
        [-1.5760675e-01,  1.0587387e+00,  9.2773572e-02],
        ...,
        [ 4.2519888e-01, -6.64527

In [49]:
tensor_h[2::]

<tf.Tensor: shape=(2, 100, 100, 3), dtype=float32, numpy=
array([[[[-0.08405042, -0.27636537,  1.1700271 ],
         [-0.76800317,  0.8091497 ,  1.301402  ],
         [-0.11555251, -0.2487025 , -1.0055829 ],
         ...,
         [-0.8848772 , -0.07380464,  0.4978555 ],
         [ 2.246356  ,  0.2594977 ,  0.7953565 ],
         [ 0.43940493, -1.2573774 ,  1.0917153 ]],

        [[-0.12998809,  1.0319464 ,  0.7013286 ],
         [ 0.10239486,  1.078078  ,  0.25875124],
         [ 0.39264607, -0.5500014 , -0.28221053],
         ...,
         [-1.7875882 , -0.57350636,  0.8004925 ],
         [ 0.6355311 ,  0.9365277 ,  0.6139376 ],
         [ 1.555401  , -0.24069063,  0.46892247]],

        [[ 1.2148111 ,  0.43184167,  1.2464398 ],
         [ 1.8281003 , -0.8009524 , -1.4048351 ],
         [-0.2373528 , -0.26428616,  0.43108147],
         ...,
         [-0.20712548,  0.58193856,  1.3803394 ],
         [-0.30526587, -1.1549222 ,  1.1365173 ],
         [ 0.7731123 , -0.21877277,  0.0391746

In [50]:
tensor_h[::-1]

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[ 1.13952720e+00,  1.66621530e+00, -1.05322075e+00],
         [ 1.92328715e+00,  9.24117863e-01,  7.32302725e-01],
         [-8.15660715e-01,  4.74828124e-01, -8.15978944e-01],
         ...,
         [-5.37479103e-01,  1.84456170e+00, -4.23272818e-01],
         [ 5.72206736e-01,  1.36583552e-01, -4.61716264e-01],
         [ 6.76471710e-01,  5.15136480e-01,  5.32108545e-01]],

        [[ 1.48215020e+00,  5.40702462e-01,  1.93026945e-01],
         [ 6.60500109e-01, -6.11198127e-01,  2.01554084e+00],
         [ 9.51299548e-01, -7.44174361e-01, -1.20876813e+00],
         ...,
         [ 9.32939231e-01, -7.63930023e-01,  1.34204969e-01],
         [-5.53817339e-02, -7.01639473e-01, -7.53005922e-01],
         [-1.56066668e+00, -1.41635549e+00, -6.11722410e-01]],

        [[ 2.31538802e-01,  9.13060755e-02, -2.01150909e-01],
         [-2.00673833e-01, -1.34280097e+00, -1.79315543e+00],
         [ 6.21562839e-01,  1.33926582e+00

In [51]:
tensor_h[0][10][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.023026574>

In [52]:
indices = [0,1,3]
tf.gather(tensor_h, axis=0, indices=indices,  batch_dims=1)

<tf.Tensor: shape=(3, 100, 100, 3), dtype=float32, numpy=
array([[[[ 6.53053895e-02,  1.16006529e+00, -1.83976543e+00],
         [-1.35930789e+00, -1.00495124e+00, -1.21588933e+00],
         [-6.46750152e-01, -8.22716594e-01, -1.13273835e+00],
         ...,
         [ 6.94982350e-01,  3.07627702e+00, -1.73715148e-02],
         [-1.41668066e-01,  1.94768488e+00, -2.64783561e-01],
         [-2.20702648e-01, -1.73206255e-01, -4.03073817e-01]],

        [[-7.13319838e-01, -1.09166205e+00, -1.62083089e+00],
         [-4.60682273e-01,  1.88821721e+00, -4.50883567e-01],
         [ 1.51073337e-01,  1.30773175e+00, -1.52539283e-01],
         ...,
         [ 1.16286695e+00,  8.69000256e-01,  2.15855539e-01],
         [-1.07942915e+00,  1.15526688e+00,  7.77809441e-01],
         [-1.42557994e-02,  2.45075434e-01, -5.87552547e-01]],

        [[ 2.34675837e+00, -5.80247976e-02, -1.09814060e+00],
         [ 4.68621373e-01,  1.52858782e+00,  5.42201042e-01],
         [-1.78422555e-01,  1.12338901e+00

In [53]:
indices = [0,1,1,0], [1,2,2,0]
tf.gather_nd(tensor_h, indices=indices)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.46068227, -0.5251295 ], dtype=float32)>

In [54]:
const_d_1 = tf.constant([[1,2,3,4]],shape=[2,2], dtype=tf.int32)
print(const_d_1.shape)
print(const_d_1.get_shape())
print(tf.shape(const_d_1))

(2, 2)
(2, 2)
tf.Tensor([2 2], shape=(2,), dtype=int32)


In [55]:
reshape_1 = tf.constant([[1,2,3,],
                        [4,5,6]])
print(reshape_1)
tf.reshape(reshape_1, (3,2))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [56]:
expand_sample_1 = tf.random.normal([100,100,3], seed=1)
print("size of the original data:", expand_sample_1.shape)
print('add dimension before the first dimention (axis=0): ', tf.expand_dims(expand_sample_1, axis=0).shape)
print("add a dimension before the second dimention (axis=1): ", tf.expand_dims(expand_sample_1, axis=1).shape)

size of the original data: (100, 100, 3)
add dimension before the first dimention (axis=0):  (1, 100, 100, 3)
add a dimension before the second dimention (axis=1):  (100, 1, 100, 3)


In [57]:
squeeze_sample_1 = tf.random.normal([1,100,100,3])
print("size of the original data:", squeeze_sample_1.shape)
squeezed_sample_1 = tf.squeeze(squeeze_sample_1)
print("data size after dimension squeezing: ", squeezed_sample_1.shape)

size of the original data: (1, 100, 100, 3)
data size after dimension squeezing:  (100, 100, 3)


In [58]:
trans_1 = tf.constant([1,2,3,4,5,6], shape=[2,3])
print("size of the original data:", trans_1.shape)
transposed_1 = tf.transpose(trans_1)
print("size of transposed data:", transposed_1.shape)

size of the original data: (2, 3)
size of transposed data: (3, 2)


In [59]:
trans_2 = tf.random.normal([4,100,100,3])
print("size of the original data:", trans_2.shape)
transposed_2 = tf.transpose(trans_2)
print("size of transposed data:", trans_2.shape)

size of the original data: (4, 100, 100, 3)
size of transposed data: (4, 100, 100, 3)


In [60]:
broadcast_sample_1 = tf.constant([1,2,3,4,5,6])
print("original data:", broadcast_sample_1.numpy())
broadcasted_sample = tf.broadcast_to(broadcast_sample_1, shape=[4,6])
print("broadcasted data:", broadcasted_sample.numpy())

original data: [1 2 3 4 5 6]
broadcasted data: [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [61]:
a = tf.constant([[0,0,0],
                [10,10,10],
                [20,20,20],
                [30,30,30]])
b = tf.constant([1,2,3])
print(a+b)

tf.Tensor(
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]], shape=(4, 3), dtype=int32)


In [62]:
a = tf.constant([[3,5],
               [4,8]])
b = tf.constant([[1,6],
                [2,9]])
print(tf.add(a,b))

tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


In [63]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 63],
       [20, 96]])>

In [64]:
argmax_sample_1 = tf.constant([[1,3,2],
                              [2,5,8],
                              [7,5,9]])
print("input tensor:", argmax_sample_1.numpy())
max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)
print("Searches for the position of the maximum value by column:", max_sample_1.numpy())
print("Searches for the position of the maximum value by row:", max_sample_2.numpy())

input tensor: [[1 3 2]
 [2 5 8]
 [7 5 9]]
Searches for the position of the maximum value by column: [2 1 2]
Searches for the position of the maximum value by row: [1 2 2]


In [68]:
reduce_sample_1 = tf.constant([1,2,3,4,5,6], shape=[2,3])
print("raw data:", reduce_sample_1.numpy())
print("calculate the sum (axis=None):",
      tf.reduce_sum(reduce_sample_1,axis=None).numpy())
print("calculate the sum of each column by column (axis=0):", 
      tf.reduce_sum(reduce_sample_1, 0).numpy())
print("calculate the sum of each column by row (axis=1):", 
      tf.reduce_sum(reduce_sample_1, 1).numpy())

raw data: [[1 2 3]
 [4 5 6]]
calculate the sum (axis=None): 21
calculate the sum of each column by column (axis=0): [5 7 9]
calculate the sum of each column by row (axis=1): [ 6 15]


In [69]:
import numpy as np

split_sample1 = tf.random.normal([10,100,100,3])
print("size of the original data:",
     split_sample1.shape)

splited_sample1 = tf.split(split_sample1, num_or_size_splits=5, axis=0)
print("size of the split data when num_or_size_split is set to 10:",
     np.shape(splited_sample1))

splited_sample2 = tf.split(split_sample1, num_or_size_splits=[3,5,2], axis=0)
print("when num_or_size_splits=[3,5,2], the size of the splits data is:",
     np.shape(splited_sample2[0]), np.shape(splited_sample2[1]),
     np.shape(splited_sample2[2]))

size of the original data: (10, 100, 100, 3)
size of the split data when num_or_size_split is set to 10: (5, 2, 100, 100, 3)
when num_or_size_splits=[3,5,2], the size of the splits data is: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


In [70]:
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2= tf.random.normal([40,100,100,3])
print("Sizes the original data:", concat_sample_1.shape, concat_sample_2.shape)
concated_sample_1 = tf.concat([concat_sample_1,concat_sample_2], 0)
print("Sizes of the data after concatenation:", concated_sample_1.shape)

Sizes the original data: (4, 100, 100, 3) (40, 100, 100, 3)
Sizes of the data after concatenation: (44, 100, 100, 3)


In [71]:
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])
print("Sizes of the original data:", stack_sample_1.shape, stack_sample_2.shape)
stacked_sample = tf.stack([stack_sample_1, stack_sample_2], 0)
print("Data size after concatenation:", stacked_sample.shape)

Sizes of the original data: (100, 100, 3) (100, 100, 3)
Data size after concatenation: (2, 100, 100, 3)


In [72]:
tf.unstack(stacked_sample, axis=0)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[-0.14166011,  0.3948017 , -0.23218855],
         [-0.9118336 , -0.34304756,  0.70931834],
         [-0.44427955,  0.33715102, -1.1853049 ],
         ...,
         [ 1.5270624 ,  1.2627944 ,  1.0867856 ],
         [ 1.2099762 ,  0.93261814,  1.3896598 ],
         [ 0.61118156, -1.2403554 ,  0.8107824 ]],
 
        [[ 0.04606659,  0.16283575, -0.9297925 ],
         [ 0.20384568,  1.5117546 ,  0.10964221],
         [ 1.8801275 , -1.0871006 ,  0.5278556 ],
         ...,
         [-1.1059833 , -1.12903   ,  0.17676133],
         [-1.7774109 ,  1.2065482 , -0.6823158 ],
         [ 2.8089857 , -0.8008205 , -1.3074212 ]],
 
        [[ 1.5638763 ,  1.458271  ,  2.1028175 ],
         [-0.78556937,  0.32048473,  0.5391402 ],
         [ 0.09677304, -1.795815  , -0.94570476],
         ...,
         [ 0.7935951 ,  1.7465968 ,  0.7553859 ],
         [-2.0270834 ,  0.1580276 , -0.8025464 ],
         [-0.82802624,  0.07484981,  0.0606049

In [73]:
sort_sample1 = tf.random.shuffle(tf.range(10))
print("input tensor:", sort_sample1.numpy())
sorted_sample1 = tf.sort(sort_sample1, direction="ASCENDING")
sorted_sample2 = tf.argsort(sort_sample1, direction="ASCENDING")
print("tensor after sorting:", sorted_sample1.numpy())
print("The indexes of the element after sorting are as follows:", sorted_sample2.numpy())

input tensor: [1 6 5 0 7 8 2 4 9 3]
tensor after sorting: [0 1 2 3 4 5 6 7 8 9]
The indexes of the element after sorting are as follows: [3 0 6 9 7 2 1 4 5 8]


In [74]:
value, index = tf.nn.top_k(sort_sample1, 5)
print("input tensor:", sort_sample1.numpy())
print("The first value in ascending order are as follows:", value.numpy())
print("The first value in ascending order in ascending order:", index.numpy())

input tensor: [1 6 5 0 7 8 2 4 9 3]
The first value in ascending order are as follows: [9 8 7 6 5]
The first value in ascending order in ascending order: [8 5 4 1 2]


In [75]:
x = tf.ones((2, 2), dtype=tf.dtypes.float32) 
y = tf.constant([[1, 2], [3, 4]], dtype=tf.dtypes.float32) 
z = tf.matmul(x, y) 
print(z)

tf.Tensor(
[[4. 6.]
 [4. 6.]], shape=(2, 2), dtype=float32)


In [1]:
import tensorflow.compat.v1 as tf

In [77]:
tf.disable_eager_execution()

In [2]:
a = tf.ones((2, 2), dtype=tf.dtypes.float32) 
b = tf.constant([[1, 2], [3, 4]], dtype=tf.dtypes.float32) 
c = tf.matmul(a, b)
sess = tf.Session()
print(sess.run(c))

RuntimeError: The Session graph is empty. Add operations to the graph before calling run().

In [1]:
import tensorflow as tf

In [2]:
import numpy

In [3]:
thre_1 = tf.random.uniform([], 0, 1) 
x = tf.reshape(tf.range(0, 4), [2, 2]) 
print(thre_1) 
if thre_1.numpy() > 0.5: 
    y = tf.matmul(x, x) 
else: 
    y = tf.add(x, x)

tf.Tensor(0.63459444, shape=(), dtype=float32)


In [4]:
@tf.function
def simple_nn_layer(w,x,b): 
    return tf.nn.relu(tf.matmul(w, x)+b) 

w = tf.random.uniform((3, 3)) 
x = tf.random.uniform((3, 3)) 
b = tf.constant(0.5, dtype='float32') 
simple_nn_layer(w,x,b)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.1632192, 1.7804871, 2.4565797],
       [1.0060475, 1.388504 , 2.0112486],
       [1.0243807, 1.5628603, 1.9016252]], dtype=float32)>

In [5]:
CNN_layer = tf.keras.layers.Conv2D(100, 2, strides=(1,1)) 

In [6]:
@tf.function
def CNN_fn(image):
  return CNN_layer(image)

In [7]:
image = tf.zeros([100, 200, 200, 3]) 

In [8]:
CNN_layer(image)
CNN_fn(image)

<tf.Tensor: shape=(100, 199, 199, 100), dtype=float32, numpy=
array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., 

In [9]:
import timeit

In [ ]:
print("time required for performing the computation of one convolutional neural network (CNN) layer in eager execution mode:", timeit.timeit(lambda: CNN_layer(image), number=10)) 
print("time required for performing the computation of one CNN layer in graph mode:", timeit.timeit(lambda: CNN_fn(image), number=10))